openapi: 3.0.0
info:
  title: OneDrop API
  description: The API for the OneDrop blood donation platform.
  version: 1.0.0
servers:
  - url: http://localhost:9091
paths:
  /:
    get:
      summary: Get welcome message
      description: Returns a welcome message for the OneDrop API.
      responses:
        '200':
          description: A welcome message.
          content:
            text/html:
              schema:
                type: string
                example: '<html><body><h1>Welcome to OneDrop!</h1><p>This is a blood donation platform.</p></body></html>'
